//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoCursoQtdDisciplinas
    {
        public int Codigo { get; set; }
        public string Curso { get; set; }
        public string Habilidade { get; set; }
        public string Modalidade { get; set; }
        public Nullable<int> Quantidade { get; set; }
    }
}
